from fastapi import APIRouter, Depends, HTTPException
from database import get_mongo_db
from routers.auth import get_current_user
import schemas
from motor.motor_asyncio import AsyncIOMotorDatabase
from bson import ObjectId
import google.generativeai as genai
import os
import json

router = APIRouter(prefix="/screening", tags=["screening"])

sys_prompt = """You are an expert clinical psychological AI assessor.
Analyze the user's answers to a psychological screening questionnaire.
Return ONLY a strictly valid JSON object. Do not include markdown code blocks.
The JSON must have the following exact keys and format:
{
  "readiness_score": <int between 0 and 100, where 100 is perfectly healthy and 0 is severe crisis>,
  "risk_level": "<string: must be exactly 'Low', 'Moderate', or 'Critical'>",
  "feedback": "<string: 2-3 sentences of empathetic, professional analysis and recommendations based on their answers>"
}
"""

@router.post("/submit", response_model=schemas.ScreeningResult)
async def submit_screening(
    data: schemas.ScreeningAnswers,
    current_user: schemas.User = Depends(get_current_user),
    mongo_db: AsyncIOMotorDatabase = Depends(get_mongo_db)
):
    try:
        genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
        # We enforce JSON output utilizing response_mime_type if available, or rely on strict prompt
        model = genai.GenerativeModel("gemini-2.5-flash", system_instruction=sys_prompt)
        
        # Combine user answers into a readable prompt
        user_input = "User's Screening Answers:\n"
        for i, answer in enumerate(data.answers):
            user_input += f"Q{i+1}: {answer}\n"
            
        response = await model.generate_content_async(user_input)
        response_text = response.text.strip()
        
        # Clean up any potential markdown formatting from the response
        if response_text.startswith("```json"):
            response_text = response_text[7:]
        if response_text.startswith("```"):
            response_text = response_text[3:]
        if response_text.endswith("```"):
            response_text = response_text[:-3]
            
        result_json = json.loads(response_text)
        
        new_score = int(result_json.get("readiness_score", 50))
        risk_level = result_json.get("risk_level", "Moderate")
        feedback = result_json.get("feedback", "Thank you for completing the assessment.") + " (Generated by Online AI)"
        
    except Exception as e:
        print(f"Gemini screening analysis failed: {str(e)}")
        # Dummy response if API totally fails
        # This part of the provided edit seems to be a full return, which would prevent database update.
        # Assuming the intent is to set fallback values and continue to database update.
        new_score = 60
        risk_level = "Moderate"
        feedback = "Unable to connect to AI for full analysis. Please consult a human counselor."
        # The provided edit also included "analysis" and "recommendations" keys which are not part of the schemas.ScreeningResult feedback.
        # Sticking to the schema for the feedback string.
        
    try:
        # Update user profile in database
        await mongo_db.users.update_one(
            {"_id": ObjectId(current_user.id)},
            {"$set": {"readiness_score": new_score, "risk_level": risk_level}}
        )
        
        # Construct updated user dictionary
        current_dict = current_user.model_dump()
        current_dict['readiness_score'] = new_score
        current_dict['risk_level'] = risk_level
        
        updated_user = schemas.User(**current_dict)
        
        updated_user = schemas.User(**current_dict)
        return schemas.ScreeningResult(user=updated_user, feedback=feedback)
        
    except Exception as e:
        print("Database/Server error during screening fallback:", repr(e))
        raise HTTPException(status_code=500, detail="Failed to process screening entirely.")
